#CREATE A PROGRAM THAT TAKES A FULL NAME THEN SWAPS THE FIRST AND LAST NAME
 #THEN CHANGES ALL VOWELS TO THE NEXT VOWEL
  #THEN EVERY CONSONANT TO THE NEXT CONSONANT

def spy_name(str)
  str = str.split(' ').reverse
end
