#WORD GUESSING GAME: 
#
#USER ONE INPUTS A WORD
#
#USER TWO GUESSES THE WORD ONE CHARACTER AT A TIME
#
#THE AMOUNT OF GUESSES EQUALS THE WORD LENGTH GIVEN BY USER ONE
#
#REPEATED GUESSES DON'T COUNT AS A GUESS
#
#CORRECT CHARACTERS ARE PRINTED OUT IN ORDER OF PLACEMENT IN WORD
#
#IF USER TWO GUESSES WORD CORRECTLY THEY GET A CONGRATS
#
#IF USER TWO GUESSES INCORRECTLY THEY GET A TAUNT

sdf 